# Generated by Django 4.0.6 on 2022-09-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('about', models.TextField()),
            ],
        ),
    ]
