# Generated by Django 4.0.6 on 2022-09-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentrec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.SlugField(default='stud-01'),
            preserve_default=False,
        ),
    ]
